FROM python:3.11

# 작업 디렉토리 설정
WORKDIR /app

# Git repository clone
RUN git clone https://github.com/yojulab/study_databases

WORKDIR /app/study_databases

# RUN pip install --no-cache-dir -r ./requirements.txt

RUN rm -rf .git

