version: '1.0'
services:
  app:
    container_name: python3
    build:
      context: .
      dockerfile: Dockerfile
    tty: true

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
